# Generated by Django 5.0.6 on 2024-12-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLogins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.IntegerField()),
                ('fullName', models.CharField(max_length=100)),
                ('queue', models.CharField(max_length=50)),
                ('startTime', models.IntegerField()),
                ('endTime', models.IntegerField()),
                ('server_ip', models.CharField(max_length=20)),
                ('time_id', models.IntegerField()),
                ('agent_ip', models.CharField(max_length=100)),
            ],
        ),
    ]
